### ISSUE TITLE
Sometimes share link does not have .html suffix

### ISSUE THREAD

**Issue by yilunzhang** [JithinKS97/riddle#22]
Sometimes (but not always) the link I got in the share button is
```
http://nknriddle.xyz/drawingboard?hostAddress=xxx
```
instead of
```
http://nknriddle.xyz/drawingboard.html?hostAddress=xxx
```
which results in a 404.

Also after creating a room, the current url also doesn't have the `.html` suffix, resulting a 404 if user tried to refresh page.

Maybe it's better to make sure all url are consistent and have the `.html` suffix.

**Comment by JithinKS97** [comment]
@yilunzhang Links that are obtained by share link all should have `.html` suffix in them. But directly copying from the address bar need not.

Are you saying that even the link obtained by clicking share button doesn't have html suffix?

**Comment by yilunzhang** [comment]
Yes I've reproduced once today, but somehow can't reproduce it now.

> But directly copying from the address bar need not.

This seems to be problematic IMO because if user press refresh on page, it will show 404...

**Comment by JithinKS97** [comment]
Thanks, let me see how I can improve the experience.
